name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Archive app files
        run: zip -r app.zip . -x "node_modules/*" "logs/*" "*.log" ".env*" "src/*" ".git/*" ".github/*"

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "app.zip"
          target: "${{ secrets.EC2_APP_PATH }}/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ${{ secrets.EC2_APP_PATH }}
            cd ${{ secrets.EC2_APP_PATH }}
            unzip -o app.zip
            rm -f app.zip
            npm install --production
            pm2 restart github-actions-demo || pm2 start dist/server.js --name github-actions-demo
            pm2 save
